#!/bin/sh

# ░█▀▀░█░█░█▀█░█▀█░█▀▀░█▀▀░░░▀█▀░█▀█░█▀█░█░█░▀█▀░░░█▄█░█▀▀░▀█▀░█░█░█▀█░█▀▄ Change
# ░█░░░█▀█░█▀█░█░█░█░█░█▀▀░░░░█░░█░█░█▀▀░█░█░░█░░░░█░█░█▀▀░░█░░█▀█░█░█░█░█ Input
# ░▀▀▀░▀░▀░▀░▀░▀░▀░▀▀▀░▀▀▀░░░▀▀▀░▀░▀░▀░░░▀▀▀░░▀░░░░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀░▀▀░ Method

# Project Name   - CIM (Change Input Method)
# Created On     - 07/02/21, 09:17:00 AM
# Author Name    - MD. Fahim Abrar Saikat
# Author E-mail  - saikat.cucse.52@gmail.com
# Author Github  - https://github.com/FA-Saikat


# Add all the input methods that you want to toggle.
# You can get all the available ibus engines (or simply, input methods) by running
# ibus list-engine

declare -a options=(
"xkb:us::eng"
"ibus-avro"
)

# dmenu prompt to choose options
input=$(printf '%s\n' "${options[@]}" | dmenu -fn 'NotoSansMono Nerd Font:size=11' -nb '#282828' -nf '#c2c2c2' -sb '#c2c2c2' -sf '#282828' -i -l 5 -p 'Choose Keyboard:')


# Changing ibus engine to our selected method
ibus engine $input
